// Mocks generated by Mockito 5.4.6 from annotations
// in iddir_app/test/features/payment/data/repositories/payment_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:iddir_app/features/payment/data/data_sources/payment_remote_datasource.dart'
    as _i4;
import 'package:iddir_app/features/payment/data/models/payment_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentDetails_1 extends _i1.SmartFake
    implements _i3.PaymentDetails {
  _FakePaymentDetails_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaymentRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRemoteDatasource extends _i1.Mock
    implements _i4.PaymentRemoteDatasource {
  MockPaymentRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i5.Future<_i3.PaymentDetails> getPaymentDetails(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentDetails, [token]),
            returnValue: _i5.Future<_i3.PaymentDetails>.value(
              _FakePaymentDetails_1(
                this,
                Invocation.method(#getPaymentDetails, [token]),
              ),
            ),
          )
          as _i5.Future<_i3.PaymentDetails>);

  @override
  _i5.Future<List<_i3.PaymentModel>> getPendingPayments(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingPayments, [token]),
            returnValue: _i5.Future<List<_i3.PaymentModel>>.value(
              <_i3.PaymentModel>[],
            ),
          )
          as _i5.Future<List<_i3.PaymentModel>>);

  @override
  _i5.Future<bool> updatePaymentStatus({
    required String? token,
    required String? userId,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePaymentStatus, [], {
              #token: token,
              #userId: userId,
              #status: status,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String> uploadReceipt({
    required String? token,
    String? filePath,
    _i6.Uint8List? imageBytes,
    String? fileName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadReceipt, [], {
              #token: token,
              #filePath: filePath,
              #imageBytes: imageBytes,
              #fileName: fileName,
            }),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#uploadReceipt, [], {
                  #token: token,
                  #filePath: filePath,
                  #imageBytes: imageBytes,
                  #fileName: fileName,
                }),
              ),
            ),
          )
          as _i5.Future<String>);
}
