// Mocks generated by Mockito 5.4.6 from annotations
// in iddir_app/test/features/profile/data/repositories/profile_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:iddir_app/features/profile/data/data_sources/profile_remote_datasource.dart'
    as _i4;
import 'package:iddir_app/features/profile/data/models/profile_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileModel_1 extends _i1.SmartFake implements _i3.ProfileModel {
  _FakeProfileModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDatasource extends _i1.Mock
    implements _i4.ProfileRemoteDatasource {
  MockProfileRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i5.Future<_i3.ProfileModel> getProfile(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [token]),
            returnValue: _i5.Future<_i3.ProfileModel>.value(
              _FakeProfileModel_1(
                this,
                Invocation.method(#getProfile, [token]),
              ),
            ),
          )
          as _i5.Future<_i3.ProfileModel>);

  @override
  _i5.Future<_i3.ProfileModel> updateProfile(
    String? token,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [token, data]),
            returnValue: _i5.Future<_i3.ProfileModel>.value(
              _FakeProfileModel_1(
                this,
                Invocation.method(#updateProfile, [token, data]),
              ),
            ),
          )
          as _i5.Future<_i3.ProfileModel>);

  @override
  _i5.Future<String> updateProfilePicture(String? token, dynamic imageData) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePicture, [token, imageData]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#updateProfilePicture, [token, imageData]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<bool> deleteAccount(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [token]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
